const byId = (id) => document.getElementById(id);

export const ui = {
  recordButton: byId('recordButton'),
  timer: byId('timer'),
  timerHint: byId('timerHint'),
  statusPill: byId('statusPill'),
  saveButton: byId('saveButton'),
  preview: byId('preview'),
  emptyState: byId('emptyState'),
  audioPlayer: byId('audioPlayer'),
  recordingName: byId('recordingName'),
  recordingSize: byId('recordingSize'),
  recordingFormat: byId('recordingFormat'),
  recordingDuration: byId('recordingDuration'),
  recordingTimestamp: byId('recordingTimestamp'),
  errorMessage: byId('errorMessage'),
  discardButton: byId('discardButton'),
  meter: byId('levelMeter'),
  meterFill: byId('meterFill'),
  deviceSelect: byId('deviceSelect'),
  refreshDevicesButton: byId('refreshDevicesButton'),
  formatSelect: byId('formatSelect'),
  thresholdSlider: byId('thresholdSlider'),
  thresholdValue: byId('thresholdValue'),
  minimizeButton: byId('minimizeButton'),
  closeButton: byId('closeButton'),
  gateHoldSlider: byId('gateHoldSlider'),
  gateHoldValue: byId('gateHoldValue'),
  countdownToggle: byId('countdownToggle'),
  countdownSelect: byId('countdownSelect'),
  autoTrimToggle: byId('autoTrimToggle'),
  waveformCanvas: byId('waveformCanvas'),
  favoriteBadge: byId('favoriteBadge'),
  favoriteButton: byId('favoriteButton'),
  renameButton: byId('renameButton'),
  exportButton: byId('exportButton'),
  noteField: byId('noteField'),
  noteContainer: byId('noteContainer'),
  libraryList: byId('libraryList'),
  libraryEmpty: byId('libraryEmpty'),
  clearLibraryButton: byId('clearLibraryButton')
};
